
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ConvertLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ConvertLog
 * 
 */
export type ConvertLogModel = runtime.Types.Result.DefaultSelection<Prisma.$ConvertLogPayload>

export type AggregateConvertLog = {
  _count: ConvertLogCountAggregateOutputType | null
  _avg: ConvertLogAvgAggregateOutputType | null
  _sum: ConvertLogSumAggregateOutputType | null
  _min: ConvertLogMinAggregateOutputType | null
  _max: ConvertLogMaxAggregateOutputType | null
}

export type ConvertLogAvgAggregateOutputType = {
  width: number | null
  height: number | null
  size: number | null
  width_converted: number | null
  height_converted: number | null
  size_converted: number | null
}

export type ConvertLogSumAggregateOutputType = {
  width: number | null
  height: number | null
  size: number | null
  width_converted: number | null
  height_converted: number | null
  size_converted: number | null
}

export type ConvertLogMinAggregateOutputType = {
  id: string | null
  created_at: Date | null
  updated_at: Date | null
  path: string | null
  type: string | null
  type_converted: string | null
  width: number | null
  height: number | null
  size: number | null
  quality: string | null
  width_converted: number | null
  height_converted: number | null
  size_converted: number | null
  quality_converted: string | null
  result: string | null
  success: boolean | null
  error: string | null
}

export type ConvertLogMaxAggregateOutputType = {
  id: string | null
  created_at: Date | null
  updated_at: Date | null
  path: string | null
  type: string | null
  type_converted: string | null
  width: number | null
  height: number | null
  size: number | null
  quality: string | null
  width_converted: number | null
  height_converted: number | null
  size_converted: number | null
  quality_converted: string | null
  result: string | null
  success: boolean | null
  error: string | null
}

export type ConvertLogCountAggregateOutputType = {
  id: number
  created_at: number
  updated_at: number
  path: number
  type: number
  type_converted: number
  width: number
  height: number
  size: number
  quality: number
  width_converted: number
  height_converted: number
  size_converted: number
  quality_converted: number
  result: number
  success: number
  error: number
  _all: number
}


export type ConvertLogAvgAggregateInputType = {
  width?: true
  height?: true
  size?: true
  width_converted?: true
  height_converted?: true
  size_converted?: true
}

export type ConvertLogSumAggregateInputType = {
  width?: true
  height?: true
  size?: true
  width_converted?: true
  height_converted?: true
  size_converted?: true
}

export type ConvertLogMinAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  path?: true
  type?: true
  type_converted?: true
  width?: true
  height?: true
  size?: true
  quality?: true
  width_converted?: true
  height_converted?: true
  size_converted?: true
  quality_converted?: true
  result?: true
  success?: true
  error?: true
}

export type ConvertLogMaxAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  path?: true
  type?: true
  type_converted?: true
  width?: true
  height?: true
  size?: true
  quality?: true
  width_converted?: true
  height_converted?: true
  size_converted?: true
  quality_converted?: true
  result?: true
  success?: true
  error?: true
}

export type ConvertLogCountAggregateInputType = {
  id?: true
  created_at?: true
  updated_at?: true
  path?: true
  type?: true
  type_converted?: true
  width?: true
  height?: true
  size?: true
  quality?: true
  width_converted?: true
  height_converted?: true
  size_converted?: true
  quality_converted?: true
  result?: true
  success?: true
  error?: true
  _all?: true
}

export type ConvertLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConvertLog to aggregate.
   */
  where?: Prisma.ConvertLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvertLogs to fetch.
   */
  orderBy?: Prisma.ConvertLogOrderByWithRelationInput | Prisma.ConvertLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ConvertLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvertLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvertLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ConvertLogs
  **/
  _count?: true | ConvertLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ConvertLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ConvertLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ConvertLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ConvertLogMaxAggregateInputType
}

export type GetConvertLogAggregateType<T extends ConvertLogAggregateArgs> = {
      [P in keyof T & keyof AggregateConvertLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConvertLog[P]>
    : Prisma.GetScalarType<T[P], AggregateConvertLog[P]>
}




export type ConvertLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConvertLogWhereInput
  orderBy?: Prisma.ConvertLogOrderByWithAggregationInput | Prisma.ConvertLogOrderByWithAggregationInput[]
  by: Prisma.ConvertLogScalarFieldEnum[] | Prisma.ConvertLogScalarFieldEnum
  having?: Prisma.ConvertLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ConvertLogCountAggregateInputType | true
  _avg?: ConvertLogAvgAggregateInputType
  _sum?: ConvertLogSumAggregateInputType
  _min?: ConvertLogMinAggregateInputType
  _max?: ConvertLogMaxAggregateInputType
}

export type ConvertLogGroupByOutputType = {
  id: string
  created_at: Date
  updated_at: Date
  path: string
  type: string
  type_converted: string | null
  width: number | null
  height: number | null
  size: number | null
  quality: string | null
  width_converted: number | null
  height_converted: number | null
  size_converted: number | null
  quality_converted: string | null
  result: string | null
  success: boolean
  error: string | null
  _count: ConvertLogCountAggregateOutputType | null
  _avg: ConvertLogAvgAggregateOutputType | null
  _sum: ConvertLogSumAggregateOutputType | null
  _min: ConvertLogMinAggregateOutputType | null
  _max: ConvertLogMaxAggregateOutputType | null
}

type GetConvertLogGroupByPayload<T extends ConvertLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ConvertLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ConvertLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConvertLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConvertLogGroupByOutputType[P]>
      }
    >
  >



export type ConvertLogWhereInput = {
  AND?: Prisma.ConvertLogWhereInput | Prisma.ConvertLogWhereInput[]
  OR?: Prisma.ConvertLogWhereInput[]
  NOT?: Prisma.ConvertLogWhereInput | Prisma.ConvertLogWhereInput[]
  id?: Prisma.StringFilter<"ConvertLog"> | string
  created_at?: Prisma.DateTimeFilter<"ConvertLog"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ConvertLog"> | Date | string
  path?: Prisma.StringFilter<"ConvertLog"> | string
  type?: Prisma.StringFilter<"ConvertLog"> | string
  type_converted?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
  width?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  height?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  size?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  quality?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
  width_converted?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  height_converted?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  size_converted?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  quality_converted?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
  result?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
  success?: Prisma.BoolFilter<"ConvertLog"> | boolean
  error?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
}

export type ConvertLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  path?: Prisma.SortOrder
  type?: Prisma.SortOrder
  type_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrderInput | Prisma.SortOrder
  quality?: Prisma.SortOrderInput | Prisma.SortOrder
  width_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  height_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  size_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  quality_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  success?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type ConvertLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ConvertLogWhereInput | Prisma.ConvertLogWhereInput[]
  OR?: Prisma.ConvertLogWhereInput[]
  NOT?: Prisma.ConvertLogWhereInput | Prisma.ConvertLogWhereInput[]
  created_at?: Prisma.DateTimeFilter<"ConvertLog"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ConvertLog"> | Date | string
  path?: Prisma.StringFilter<"ConvertLog"> | string
  type?: Prisma.StringFilter<"ConvertLog"> | string
  type_converted?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
  width?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  height?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  size?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  quality?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
  width_converted?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  height_converted?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  size_converted?: Prisma.IntNullableFilter<"ConvertLog"> | number | null
  quality_converted?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
  result?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
  success?: Prisma.BoolFilter<"ConvertLog"> | boolean
  error?: Prisma.StringNullableFilter<"ConvertLog"> | string | null
}, "id">

export type ConvertLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  path?: Prisma.SortOrder
  type?: Prisma.SortOrder
  type_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrderInput | Prisma.SortOrder
  quality?: Prisma.SortOrderInput | Prisma.SortOrder
  width_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  height_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  size_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  quality_converted?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  success?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ConvertLogCountOrderByAggregateInput
  _avg?: Prisma.ConvertLogAvgOrderByAggregateInput
  _max?: Prisma.ConvertLogMaxOrderByAggregateInput
  _min?: Prisma.ConvertLogMinOrderByAggregateInput
  _sum?: Prisma.ConvertLogSumOrderByAggregateInput
}

export type ConvertLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.ConvertLogScalarWhereWithAggregatesInput | Prisma.ConvertLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.ConvertLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ConvertLogScalarWhereWithAggregatesInput | Prisma.ConvertLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ConvertLog"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"ConvertLog"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"ConvertLog"> | Date | string
  path?: Prisma.StringWithAggregatesFilter<"ConvertLog"> | string
  type?: Prisma.StringWithAggregatesFilter<"ConvertLog"> | string
  type_converted?: Prisma.StringNullableWithAggregatesFilter<"ConvertLog"> | string | null
  width?: Prisma.IntNullableWithAggregatesFilter<"ConvertLog"> | number | null
  height?: Prisma.IntNullableWithAggregatesFilter<"ConvertLog"> | number | null
  size?: Prisma.IntNullableWithAggregatesFilter<"ConvertLog"> | number | null
  quality?: Prisma.StringNullableWithAggregatesFilter<"ConvertLog"> | string | null
  width_converted?: Prisma.IntNullableWithAggregatesFilter<"ConvertLog"> | number | null
  height_converted?: Prisma.IntNullableWithAggregatesFilter<"ConvertLog"> | number | null
  size_converted?: Prisma.IntNullableWithAggregatesFilter<"ConvertLog"> | number | null
  quality_converted?: Prisma.StringNullableWithAggregatesFilter<"ConvertLog"> | string | null
  result?: Prisma.StringNullableWithAggregatesFilter<"ConvertLog"> | string | null
  success?: Prisma.BoolWithAggregatesFilter<"ConvertLog"> | boolean
  error?: Prisma.StringNullableWithAggregatesFilter<"ConvertLog"> | string | null
}

export type ConvertLogCreateInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  path: string
  type: string
  type_converted?: string | null
  width?: number | null
  height?: number | null
  size?: number | null
  quality?: string | null
  width_converted?: number | null
  height_converted?: number | null
  size_converted?: number | null
  quality_converted?: string | null
  result?: string | null
  success?: boolean
  error?: string | null
}

export type ConvertLogUncheckedCreateInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  path: string
  type: string
  type_converted?: string | null
  width?: number | null
  height?: number | null
  size?: number | null
  quality?: string | null
  width_converted?: number | null
  height_converted?: number | null
  size_converted?: number | null
  quality_converted?: string | null
  result?: string | null
  success?: boolean
  error?: string | null
}

export type ConvertLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  type_converted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  width_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quality_converted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ConvertLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  type_converted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  width_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quality_converted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ConvertLogCreateManyInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  path: string
  type: string
  type_converted?: string | null
  width?: number | null
  height?: number | null
  size?: number | null
  quality?: string | null
  width_converted?: number | null
  height_converted?: number | null
  size_converted?: number | null
  quality_converted?: string | null
  result?: string | null
  success?: boolean
  error?: string | null
}

export type ConvertLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  type_converted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  width_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quality_converted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ConvertLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  type_converted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  width_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size_converted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  quality_converted?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ConvertLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  path?: Prisma.SortOrder
  type?: Prisma.SortOrder
  type_converted?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
  quality?: Prisma.SortOrder
  width_converted?: Prisma.SortOrder
  height_converted?: Prisma.SortOrder
  size_converted?: Prisma.SortOrder
  quality_converted?: Prisma.SortOrder
  result?: Prisma.SortOrder
  success?: Prisma.SortOrder
  error?: Prisma.SortOrder
}

export type ConvertLogAvgOrderByAggregateInput = {
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
  width_converted?: Prisma.SortOrder
  height_converted?: Prisma.SortOrder
  size_converted?: Prisma.SortOrder
}

export type ConvertLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  path?: Prisma.SortOrder
  type?: Prisma.SortOrder
  type_converted?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
  quality?: Prisma.SortOrder
  width_converted?: Prisma.SortOrder
  height_converted?: Prisma.SortOrder
  size_converted?: Prisma.SortOrder
  quality_converted?: Prisma.SortOrder
  result?: Prisma.SortOrder
  success?: Prisma.SortOrder
  error?: Prisma.SortOrder
}

export type ConvertLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  path?: Prisma.SortOrder
  type?: Prisma.SortOrder
  type_converted?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
  quality?: Prisma.SortOrder
  width_converted?: Prisma.SortOrder
  height_converted?: Prisma.SortOrder
  size_converted?: Prisma.SortOrder
  quality_converted?: Prisma.SortOrder
  result?: Prisma.SortOrder
  success?: Prisma.SortOrder
  error?: Prisma.SortOrder
}

export type ConvertLogSumOrderByAggregateInput = {
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
  width_converted?: Prisma.SortOrder
  height_converted?: Prisma.SortOrder
  size_converted?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type ConvertLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  path?: boolean
  type?: boolean
  type_converted?: boolean
  width?: boolean
  height?: boolean
  size?: boolean
  quality?: boolean
  width_converted?: boolean
  height_converted?: boolean
  size_converted?: boolean
  quality_converted?: boolean
  result?: boolean
  success?: boolean
  error?: boolean
}, ExtArgs["result"]["convertLog"]>

export type ConvertLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  path?: boolean
  type?: boolean
  type_converted?: boolean
  width?: boolean
  height?: boolean
  size?: boolean
  quality?: boolean
  width_converted?: boolean
  height_converted?: boolean
  size_converted?: boolean
  quality_converted?: boolean
  result?: boolean
  success?: boolean
  error?: boolean
}, ExtArgs["result"]["convertLog"]>

export type ConvertLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  path?: boolean
  type?: boolean
  type_converted?: boolean
  width?: boolean
  height?: boolean
  size?: boolean
  quality?: boolean
  width_converted?: boolean
  height_converted?: boolean
  size_converted?: boolean
  quality_converted?: boolean
  result?: boolean
  success?: boolean
  error?: boolean
}, ExtArgs["result"]["convertLog"]>

export type ConvertLogSelectScalar = {
  id?: boolean
  created_at?: boolean
  updated_at?: boolean
  path?: boolean
  type?: boolean
  type_converted?: boolean
  width?: boolean
  height?: boolean
  size?: boolean
  quality?: boolean
  width_converted?: boolean
  height_converted?: boolean
  size_converted?: boolean
  quality_converted?: boolean
  result?: boolean
  success?: boolean
  error?: boolean
}

export type ConvertLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "created_at" | "updated_at" | "path" | "type" | "type_converted" | "width" | "height" | "size" | "quality" | "width_converted" | "height_converted" | "size_converted" | "quality_converted" | "result" | "success" | "error", ExtArgs["result"]["convertLog"]>

export type $ConvertLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ConvertLog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    created_at: Date
    updated_at: Date
    path: string
    type: string
    type_converted: string | null
    width: number | null
    height: number | null
    size: number | null
    quality: string | null
    width_converted: number | null
    height_converted: number | null
    size_converted: number | null
    quality_converted: string | null
    result: string | null
    success: boolean
    error: string | null
  }, ExtArgs["result"]["convertLog"]>
  composites: {}
}

export type ConvertLogGetPayload<S extends boolean | null | undefined | ConvertLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload, S>

export type ConvertLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ConvertLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ConvertLogCountAggregateInputType | true
  }

export interface ConvertLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ConvertLog'], meta: { name: 'ConvertLog' } }
  /**
   * Find zero or one ConvertLog that matches the filter.
   * @param {ConvertLogFindUniqueArgs} args - Arguments to find a ConvertLog
   * @example
   * // Get one ConvertLog
   * const convertLog = await prisma.convertLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConvertLogFindUniqueArgs>(args: Prisma.SelectSubset<T, ConvertLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ConvertLogClient<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ConvertLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConvertLogFindUniqueOrThrowArgs} args - Arguments to find a ConvertLog
   * @example
   * // Get one ConvertLog
   * const convertLog = await prisma.convertLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConvertLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ConvertLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConvertLogClient<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConvertLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvertLogFindFirstArgs} args - Arguments to find a ConvertLog
   * @example
   * // Get one ConvertLog
   * const convertLog = await prisma.convertLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConvertLogFindFirstArgs>(args?: Prisma.SelectSubset<T, ConvertLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__ConvertLogClient<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConvertLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvertLogFindFirstOrThrowArgs} args - Arguments to find a ConvertLog
   * @example
   * // Get one ConvertLog
   * const convertLog = await prisma.convertLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConvertLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ConvertLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConvertLogClient<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ConvertLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvertLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ConvertLogs
   * const convertLogs = await prisma.convertLog.findMany()
   * 
   * // Get first 10 ConvertLogs
   * const convertLogs = await prisma.convertLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const convertLogWithIdOnly = await prisma.convertLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ConvertLogFindManyArgs>(args?: Prisma.SelectSubset<T, ConvertLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ConvertLog.
   * @param {ConvertLogCreateArgs} args - Arguments to create a ConvertLog.
   * @example
   * // Create one ConvertLog
   * const ConvertLog = await prisma.convertLog.create({
   *   data: {
   *     // ... data to create a ConvertLog
   *   }
   * })
   * 
   */
  create<T extends ConvertLogCreateArgs>(args: Prisma.SelectSubset<T, ConvertLogCreateArgs<ExtArgs>>): Prisma.Prisma__ConvertLogClient<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ConvertLogs.
   * @param {ConvertLogCreateManyArgs} args - Arguments to create many ConvertLogs.
   * @example
   * // Create many ConvertLogs
   * const convertLog = await prisma.convertLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ConvertLogCreateManyArgs>(args?: Prisma.SelectSubset<T, ConvertLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ConvertLogs and returns the data saved in the database.
   * @param {ConvertLogCreateManyAndReturnArgs} args - Arguments to create many ConvertLogs.
   * @example
   * // Create many ConvertLogs
   * const convertLog = await prisma.convertLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ConvertLogs and only return the `id`
   * const convertLogWithIdOnly = await prisma.convertLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ConvertLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ConvertLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ConvertLog.
   * @param {ConvertLogDeleteArgs} args - Arguments to delete one ConvertLog.
   * @example
   * // Delete one ConvertLog
   * const ConvertLog = await prisma.convertLog.delete({
   *   where: {
   *     // ... filter to delete one ConvertLog
   *   }
   * })
   * 
   */
  delete<T extends ConvertLogDeleteArgs>(args: Prisma.SelectSubset<T, ConvertLogDeleteArgs<ExtArgs>>): Prisma.Prisma__ConvertLogClient<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ConvertLog.
   * @param {ConvertLogUpdateArgs} args - Arguments to update one ConvertLog.
   * @example
   * // Update one ConvertLog
   * const convertLog = await prisma.convertLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ConvertLogUpdateArgs>(args: Prisma.SelectSubset<T, ConvertLogUpdateArgs<ExtArgs>>): Prisma.Prisma__ConvertLogClient<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ConvertLogs.
   * @param {ConvertLogDeleteManyArgs} args - Arguments to filter ConvertLogs to delete.
   * @example
   * // Delete a few ConvertLogs
   * const { count } = await prisma.convertLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ConvertLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, ConvertLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConvertLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvertLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ConvertLogs
   * const convertLog = await prisma.convertLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ConvertLogUpdateManyArgs>(args: Prisma.SelectSubset<T, ConvertLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConvertLogs and returns the data updated in the database.
   * @param {ConvertLogUpdateManyAndReturnArgs} args - Arguments to update many ConvertLogs.
   * @example
   * // Update many ConvertLogs
   * const convertLog = await prisma.convertLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ConvertLogs and only return the `id`
   * const convertLogWithIdOnly = await prisma.convertLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ConvertLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ConvertLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ConvertLog.
   * @param {ConvertLogUpsertArgs} args - Arguments to update or create a ConvertLog.
   * @example
   * // Update or create a ConvertLog
   * const convertLog = await prisma.convertLog.upsert({
   *   create: {
   *     // ... data to create a ConvertLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ConvertLog we want to update
   *   }
   * })
   */
  upsert<T extends ConvertLogUpsertArgs>(args: Prisma.SelectSubset<T, ConvertLogUpsertArgs<ExtArgs>>): Prisma.Prisma__ConvertLogClient<runtime.Types.Result.GetResult<Prisma.$ConvertLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ConvertLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvertLogCountArgs} args - Arguments to filter ConvertLogs to count.
   * @example
   * // Count the number of ConvertLogs
   * const count = await prisma.convertLog.count({
   *   where: {
   *     // ... the filter for the ConvertLogs we want to count
   *   }
   * })
  **/
  count<T extends ConvertLogCountArgs>(
    args?: Prisma.Subset<T, ConvertLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConvertLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ConvertLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvertLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ConvertLogAggregateArgs>(args: Prisma.Subset<T, ConvertLogAggregateArgs>): Prisma.PrismaPromise<GetConvertLogAggregateType<T>>

  /**
   * Group by ConvertLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConvertLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ConvertLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConvertLogGroupByArgs['orderBy'] }
      : { orderBy?: ConvertLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ConvertLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetConvertLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ConvertLog model
 */
readonly fields: ConvertLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ConvertLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConvertLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ConvertLog model
 */
export interface ConvertLogFieldRefs {
  readonly id: Prisma.FieldRef<"ConvertLog", 'String'>
  readonly created_at: Prisma.FieldRef<"ConvertLog", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"ConvertLog", 'DateTime'>
  readonly path: Prisma.FieldRef<"ConvertLog", 'String'>
  readonly type: Prisma.FieldRef<"ConvertLog", 'String'>
  readonly type_converted: Prisma.FieldRef<"ConvertLog", 'String'>
  readonly width: Prisma.FieldRef<"ConvertLog", 'Int'>
  readonly height: Prisma.FieldRef<"ConvertLog", 'Int'>
  readonly size: Prisma.FieldRef<"ConvertLog", 'Int'>
  readonly quality: Prisma.FieldRef<"ConvertLog", 'String'>
  readonly width_converted: Prisma.FieldRef<"ConvertLog", 'Int'>
  readonly height_converted: Prisma.FieldRef<"ConvertLog", 'Int'>
  readonly size_converted: Prisma.FieldRef<"ConvertLog", 'Int'>
  readonly quality_converted: Prisma.FieldRef<"ConvertLog", 'String'>
  readonly result: Prisma.FieldRef<"ConvertLog", 'String'>
  readonly success: Prisma.FieldRef<"ConvertLog", 'Boolean'>
  readonly error: Prisma.FieldRef<"ConvertLog", 'String'>
}
    

// Custom InputTypes
/**
 * ConvertLog findUnique
 */
export type ConvertLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * Filter, which ConvertLog to fetch.
   */
  where: Prisma.ConvertLogWhereUniqueInput
}

/**
 * ConvertLog findUniqueOrThrow
 */
export type ConvertLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * Filter, which ConvertLog to fetch.
   */
  where: Prisma.ConvertLogWhereUniqueInput
}

/**
 * ConvertLog findFirst
 */
export type ConvertLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * Filter, which ConvertLog to fetch.
   */
  where?: Prisma.ConvertLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvertLogs to fetch.
   */
  orderBy?: Prisma.ConvertLogOrderByWithRelationInput | Prisma.ConvertLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConvertLogs.
   */
  cursor?: Prisma.ConvertLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvertLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvertLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConvertLogs.
   */
  distinct?: Prisma.ConvertLogScalarFieldEnum | Prisma.ConvertLogScalarFieldEnum[]
}

/**
 * ConvertLog findFirstOrThrow
 */
export type ConvertLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * Filter, which ConvertLog to fetch.
   */
  where?: Prisma.ConvertLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvertLogs to fetch.
   */
  orderBy?: Prisma.ConvertLogOrderByWithRelationInput | Prisma.ConvertLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConvertLogs.
   */
  cursor?: Prisma.ConvertLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvertLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvertLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConvertLogs.
   */
  distinct?: Prisma.ConvertLogScalarFieldEnum | Prisma.ConvertLogScalarFieldEnum[]
}

/**
 * ConvertLog findMany
 */
export type ConvertLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * Filter, which ConvertLogs to fetch.
   */
  where?: Prisma.ConvertLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConvertLogs to fetch.
   */
  orderBy?: Prisma.ConvertLogOrderByWithRelationInput | Prisma.ConvertLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ConvertLogs.
   */
  cursor?: Prisma.ConvertLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConvertLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConvertLogs.
   */
  skip?: number
  distinct?: Prisma.ConvertLogScalarFieldEnum | Prisma.ConvertLogScalarFieldEnum[]
}

/**
 * ConvertLog create
 */
export type ConvertLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * The data needed to create a ConvertLog.
   */
  data: Prisma.XOR<Prisma.ConvertLogCreateInput, Prisma.ConvertLogUncheckedCreateInput>
}

/**
 * ConvertLog createMany
 */
export type ConvertLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ConvertLogs.
   */
  data: Prisma.ConvertLogCreateManyInput | Prisma.ConvertLogCreateManyInput[]
}

/**
 * ConvertLog createManyAndReturn
 */
export type ConvertLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * The data used to create many ConvertLogs.
   */
  data: Prisma.ConvertLogCreateManyInput | Prisma.ConvertLogCreateManyInput[]
}

/**
 * ConvertLog update
 */
export type ConvertLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * The data needed to update a ConvertLog.
   */
  data: Prisma.XOR<Prisma.ConvertLogUpdateInput, Prisma.ConvertLogUncheckedUpdateInput>
  /**
   * Choose, which ConvertLog to update.
   */
  where: Prisma.ConvertLogWhereUniqueInput
}

/**
 * ConvertLog updateMany
 */
export type ConvertLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ConvertLogs.
   */
  data: Prisma.XOR<Prisma.ConvertLogUpdateManyMutationInput, Prisma.ConvertLogUncheckedUpdateManyInput>
  /**
   * Filter which ConvertLogs to update
   */
  where?: Prisma.ConvertLogWhereInput
  /**
   * Limit how many ConvertLogs to update.
   */
  limit?: number
}

/**
 * ConvertLog updateManyAndReturn
 */
export type ConvertLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * The data used to update ConvertLogs.
   */
  data: Prisma.XOR<Prisma.ConvertLogUpdateManyMutationInput, Prisma.ConvertLogUncheckedUpdateManyInput>
  /**
   * Filter which ConvertLogs to update
   */
  where?: Prisma.ConvertLogWhereInput
  /**
   * Limit how many ConvertLogs to update.
   */
  limit?: number
}

/**
 * ConvertLog upsert
 */
export type ConvertLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * The filter to search for the ConvertLog to update in case it exists.
   */
  where: Prisma.ConvertLogWhereUniqueInput
  /**
   * In case the ConvertLog found by the `where` argument doesn't exist, create a new ConvertLog with this data.
   */
  create: Prisma.XOR<Prisma.ConvertLogCreateInput, Prisma.ConvertLogUncheckedCreateInput>
  /**
   * In case the ConvertLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConvertLogUpdateInput, Prisma.ConvertLogUncheckedUpdateInput>
}

/**
 * ConvertLog delete
 */
export type ConvertLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
  /**
   * Filter which ConvertLog to delete.
   */
  where: Prisma.ConvertLogWhereUniqueInput
}

/**
 * ConvertLog deleteMany
 */
export type ConvertLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConvertLogs to delete
   */
  where?: Prisma.ConvertLogWhereInput
  /**
   * Limit how many ConvertLogs to delete.
   */
  limit?: number
}

/**
 * ConvertLog without action
 */
export type ConvertLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConvertLog
   */
  select?: Prisma.ConvertLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConvertLog
   */
  omit?: Prisma.ConvertLogOmit<ExtArgs> | null
}
